### ISSUE TITLE
Blender 2.8 compatibility?

### ISSUE THREAD

**Issue by bda65** [baldingwizard/Blender-Addons#1]
Hi,
Do you plan to update your addons for blender 2.8?

**Comment by baldingwizard** [comment]
Yes - I’m looking into the differences with the Blender API for 2.8.

**Comment by bda65** [comment]
Great :)
I'm waiting...

**Comment by baldingwizard** [comment]
The NodeCustomGroup seems to behave differently in Blender2.8 or Blender2.8 is broken in this respect. I've tried the latest beta and still having problems. It also seems that Eevee doesn't support getting input from the NodeCustomGroup at all (so Cycles only at the moment). Looking into other ways of achieving this on 2.8.

**Comment by baldingwizard** [comment]
I've been working on this but it seems Blender 2.8(beta) doesn't play well with NodeCustomGroups at the moment... so using the same method as the previous version isn't working. It could be the case that the final release of 2.8 might fix this but I don't know at present (certainly the latest build doesn't work properly with this). I've got some ideas on the way forward and hopefully will have a working version shortly.

**Comment by baldingwizard** [comment]
Uploaded an (unfinished) version that provides the basic functionality on Blender 2.8 - available as https://github.com/baldingwizard/Blender-Addons/blob/master/MathsExpressionBlender28.zip. This provides the functionality in a different form - as an operator available directly on the Add menu - as well as the original 'custom node'. The 'custom node' method has incompatibilities still and will likely be removed - it's only still there while I'm still working on the operator method (which doesn't yet allow 'edit' of an existing node, only 'create new').

**Comment by baldingwizard** [comment]
Uploaded an updated version of MathsExpressionBlender28.zip. Still work-in-progress but allows creation and edit of node groups via operators (which are available on the Add menu in the node editor).

**Comment by baldingwizard** [comment]
MathsExpression add-on now updated to work with Blender 2.8 - with improvements to workflow to provide better editability and compatibility. Also, enhanced Particles To Path to be compatible with 2.8.
