### ISSUE TITLE
Error when trying to utilize the addon

### ISSUE THREAD

**Issue by Maerkus** [baldingwizard/Blender-Addons#10]
It says in the code this when trying to utilize it

AttributeError: 'IndentationError' object has no attribute 'msg'
Error: Python script failed, check the message in the system console

i don't know what that means

**Comment by baldingwizard** [comment]
Hi @Maerkus. Please can you provide me with some details. First, what version of Blender are you using? How did you download and install the add-on (was it from the ZIP file (in which case, which one?) and did you use the Blender 'Install from Zip' button in the add-on preferences or did you install it manually?). Have you tried to modify the source code at all? (perhaps to try and fix a previously reported error?). How are you trying to run it? (should be able to just choose the operator from the operator list). Thanks, Rich

**Comment by Maerkus** [comment]
I was using Blender 2.8 and i used this script
![image](https://user-images.githubusercontent.com/48921592/67770211-3d0e7580-fa56-11e9-8093-9a6fd884fb80.png)

**Comment by Maerkus** [comment]
I have installed the addon instead now through the zip file and i am using blender 2.8, but a new error now shows up
![image](https://user-images.githubusercontent.com/48921592/67787550-114cb900-fa71-11e9-802a-ea78774c6a66.png)

**Comment by manorius** [comment]
Hi @baldingwizard I'm having the same issue on 2.83. I created a one vertex object and emit one particle per frame with no velocity or Field weights, I run the simulation and then select from the ADD menu the Particles to Nurbs option and I get the same error as @Maerkus 

    Traceback (most recent call last): 
    File "C:\Users\manor\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\ParticlesToPath28\__init__.py", line 
    87, 
    in execute
    ParticlesToPath_Operator.execute_main(self, context)
    
    File "C:\Users\manor\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\ParticlesToPath28\__init__.py", line 
    109, in execute_main
   
    ParticlesToPath.createCurveFromParticles(object_selected[0].name, particleSystem=operator.particle_system-1, 
    curveResolution=operator.curve_resolution,bevelResolution=operator.bevel_resolution,fillMode='FULL')
    
    File "C:\Users\manor\AppData\Roaming\Blender 
    
    Foundation\Blender\2.83\scripts\addons\ParticlesToPath28\particles_to_path.py", line 21, in createCurveFromParticles
    eval_ob = bpy.context.depsgraph.objects.get(object.name, None)
    
    AttributeError: 'Context' object has no attribute 'depsgraph'

    location: <unknown location>:-1

**Comment by baldingwizard** [comment]
Hi @manorius - thanks for the feedback. I realise what's going on here now. I didn't realise it was the ParticlesToPath add-on that @Maerkus was reporting on (I should have examined the screenshot in more detail) so I didn't understand the situation. I understand now - the Blender API has changed sometime after 2.80, causing the problem. I'll look into how this should be done under the new API and see if I can issue a fix.

**Comment by manorius** [comment]
@Maerkus that's great news! Thanks for looking into this! ParticlesToPath is a great plugin!

**Comment by baldingwizard** [comment]
@Maerkus @manorius I've just uploaded a version of Particles to Path that's compatible with Blender 2.81. Apologies for the long delay in providing this - and thank you for your time to report the original problem. It turns out that there was an API call change in version 2.81 and the fix was actually quite straightforward in the end. I've created a separate 'ParticlesToPath281.zip' version that you should now be able to download from the Wiki. Hope this fixes your problem - and let me know if you spot any other issues.
