### ISSUE TITLE
Update node expression for 3.1?

### ISSUE THREAD

**Issue by Michaelwhite34** [baldingwizard/Blender-Addons#15]
It's available on blendermarket now,but I don't have us paypal account(it's not convenient in my country).
Do you plan to release it later?

**Comment by Michaelwhite34** [comment]
Never mind,my friend happens to have paypal account- -

**Comment by baldingwizard** [comment]
I've not had much time to spend on this due to personal issues so apologies. I do plan on updating github with the latest version when I get the chance but need to organise all the different versions and compatibility with all the different blender versions.
